### ISSUE TITLE
Nothing appearing in drawer

### ISSUE THREAD

**Issue by paulstevenuk** [chucklorenz/adapt-aboutUs#2]
I am testing this in v2.0.9 of the framework with the latest version of the Authoring Tool. I have added the extension and was able to customise it via Project Settings but I do not get any drawer icon. I then added the Resources extension and then the drawer icon appeared but when I click on this I only see the resources I have added and nothing related to the About us content.

Any ideas why it is not appearing? I am not getting any console errors.

**Comment by hbaileylxd** [comment]
Hi Paul - working fine for me with 2.0.9 and 0.1.8.

Can you post a screenshot of your About-Us settings?

**Comment by paulstevenuk** [comment]
Thanks for replying so quickly.

Grab attached here: http://pamelasteven.com/about_settings.jpg
![about_settings](https://cloud.githubusercontent.com/assets/10856676/14992635/e716730a-115e-11e6-84b5-3aad73c64d76.jpg)

**Comment by hbaileylxd** [comment]
Try adding a text item see if that helps?
